language: node_js
sudo: false
node_js:
  - "8"
cache: yarn
install:
  - yarn install

# Following is used to create a mongo db user then run mongodb. This should be uncommented when Functionnal testing will be ready

# services:
#  - mongodb
#before_script:
#  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

env:
    - NODE_ENV=dev
    - EXIT_COMMAND=exit
script:
  - yarn lint

  # - npm test : A decommenter une fois que les mock seront en place pour éviter de générer des erreurs.
