language: node_js
sudo: false
node_js:
  - "8"
cache: yarn
install:
  - yarn install

# Following is used to create a mongo db user then run mongodb. This should be uncommented when Functionnal testing will be ready

# services:
#  - mongodb
#before_script:
#  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

env:
  global:
    - NODE_ENV=dev
    - EXIT_COMMAND=exit
script:
  - yarn lint
  - yarn test

# Following is for activity tracking over Discord Webhook.

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL