version: '3.5'
volumes:
    dbdata: ~
services:
    node:
        image: node:10-alpine
        user: node
        hostname: node
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 127.0.0.1:3000:3000
        stdin_open: true
        tty: true
        entrypoint: ["node", "app.js"]
        depends_on:
          - mongo
          - redis
    mongo:
        image: mongo:4.0-xenial
        hostname: mongo
        volumes:
            - dbdata:/data/db
        env_file:
            - .env
        ports:
            - 127.0.0.1:27017:27017
    redis:
        image: redis:5-alpine
        hostname: redis
        ports:
            - 127.0.0.1:6379:6379
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 127.0.0.1:8081:8081
