version: '3.5'
volumes:
    dbdata: ~
services:
    node:
        image: node:10-alpine
        user: node
        hostname: node
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 127.0.0.1:3000:3000
        stdin_open: true
        tty: true
        entrypoint: ["node", "app.js"]
        depends_on:
          - mongo
    mongo:
        image: mongo:4.0-xenial
        hostname: mongo
        volumes:
            - dbdata:/data/db
        env_file:
            - .env
        ports:
            - 127.0.0.1:27017:27017
