version: '3.5'
volumes:
    dbdata: ~
services:
    node:
        build: .
        command: yarn start dev
        volumes:
            - ./:/usr/scr/app
        ports:
            - 127.0.0.1:3000:3000
        stdin_open: true
        tty: true
        depends_on:
          - mongo
    mongo:
        image: mongo:4.0-xenial
        hostname: mongo
        volumes:
            - dbdata:/data/db
        env_file:
            - .env
        ports:
            - 127.0.0.1:27017:27017
