version: '3.5'
services:
    node:
        build: .
        ports:
            - 127.0.0.1:3000:3000
        stdin_open: true
        tty: true
        depends_on:
          - mongo
          - redis
          - redis-commander
    mongo:
        image: mongo:xenial
        hostname: mongo
        volumes:
            - ./db:/data/db
        env_file:
            - .env
        ports:
            - 127.0.0.1:27017:27017
    redis:
        image: redis:alpine
        hostname: redis
        ports:
            - 127.0.0.1:6379:6379
        depends_on:
          - mongo
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 127.0.0.1:8081:8081
        depends_on:
          - redis
