version: '3.5'
services:
    node:
        build: .
        stdin_open: true
        tty: true
        depends_on:
            - mongo
            - redis
    mongo:
        image: mongo:4.0.12-xenial
        hostname: mongo
        volumes:
            - data-volume:/data/db
        env_file:
            - .env
    redis:
        image: redis:5.0.5-alpine
        volumes:
            - data-volume:/data
        hostname: redis
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: redis-commander
        depends_on:
            - redis
volumes:
    data-volume:
