version: '3.5'
networks:
    app: ~
volumes:
    dbdata: ~
services:
    node:
        image: node:8-alpine
        user: node
        hostname: ${COMPOSE_PROJECT_NAME}-node
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        env_file:
            - .env
        networks:
            - app
        stdin_open: true
        tty: true
        command: "yarn start"
        restart: unless-stopped
    mongo:
        image: mongo:3.6
        hostname: ${COMPOSE_PROJECT_NAME}-mongo
        volumes:
            - dbdata:/data/db
        env_file:
            - .env
        networks:
            - app
        ports:
            - 127.0.0.1:27017:27017
        restart: unless-stopped
